import fs from 'node:fs';
import path from 'node:path';

export function buildDashboardHtml({ evidence, targets, stats, generatedAt = new Date().toISOString() }) {
  const data = JSON.stringify({ evidence, targets, stats, generatedAt }).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Family Evidence Engine</title><style>
  :root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171714;background:#f4f0e8;line-height:1.45}*{box-sizing:border-box}body{margin:0}header{padding:36px clamp(18px,5vw,64px);background:#171714;color:#f7f3e8;border-bottom:6px solid #a4492f}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-size:12px;color:#d9b27c}.lede{color:#c9c6bd}h1,h2,h3{font-family:Georgia,serif}h1{font-size:clamp(36px,6vw,64px);line-height:1;margin:.25rem 0}.rule{margin-top:18px;padding:12px;border:1px solid #565248;max-width:720px;background:#24241f}main{padding:26px clamp(16px,4vw,52px) 60px}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.stat,.card,aside{background:#fffaf0;border:1px solid #d7cebf}.stat{padding:16px}.stat b{display:block;font:700 28px Georgia,serif}.stat span{font-size:11px;text-transform:uppercase;letter-spacing:.08em}.toolbar{display:flex;gap:10px;margin:18px 0}.toolbar input,.toolbar select{padding:11px;border:1px solid #b8b1a6;background:#fffaf0}.toolbar input{flex:1}.grid{display:grid;grid-template-columns:260px minmax(0,1fr);gap:20px}aside{padding:16px;height:max-content}.target{padding:10px 0;border-top:1px solid #d0c6b6}.target strong{display:block}.card{padding:17px;margin-bottom:11px;border-left:5px solid #766b5b}.card[data-tier="3"]{border-left-color:#315c46}.card[data-tier="2"]{border-left-color:#9b6a2d}.card h3{margin:.2rem 0}.meta{display:flex;flex-wrap:wrap;gap:6px}.pill{background:#e8e0d3;border:1px solid #d0c5b3;padding:3px 7px;font-size:11px;text-transform:uppercase}.land{padding:9px;background:#f0eadf;border-left:3px solid #a4492f}.warn{color:#8a2f23;font-weight:700}.source{font-size:12px;word-break:break-all}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}.toolbar input{flex-basis:100%}}
  </style></head><body><header><div class="eyebrow">Evidence-first genealogy & property intelligence</div><h1>Family Evidence Engine</h1><div class="lede">Find the person. Prove the relationship. Identify the tract. Follow the instrument.</div><div class="rule">Crawler output is a lead until the underlying record is verified. Tier 3 means primary-record candidate, not proven fact.</div></header><main><section id="stats" class="stats"></section><section class="toolbar"><input id="search" type="search" placeholder="Filter person, title, record type, land clue…"><select id="tier"><option value="">All tiers</option><option value="3">Tier 3</option><option value="2">Tier 2</option><option value="1">Tier 1</option></select><select id="type"><option value="">All record types</option></select></section><section class="grid"><aside><h2>Targets</h2><div id="targets"></div></aside><div><h2>Evidence queue <small id="count"></small></h2><div id="evidence"></div></div></section></main><script>
  const DATA=${data}; const e=DATA.evidence,s=DATA.stats,t=DATA.targets; const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  document.querySelector('#stats').innerHTML=[['Evidence',s.totalEvidence],['High confidence',s.highConfidence],['Land clues',s.landClues],['Conflict flags',s.contradictionFlags]].map(([l,v])=>'<div class="stat"><b>'+v+'</b><span>'+l+'</span></div>').join('');
  document.querySelector('#targets').innerHTML=t.map(x=>'<div class="target"><strong>'+esc(x.canonicalName)+'</strong><small>'+esc((x.places||[]).join('; '))+'</small></div>').join('');
  const types=[...new Set(e.map(x=>x.recordType))].sort(); document.querySelector('#type').insertAdjacentHTML('beforeend',types.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join(''));
  const search=document.querySelector('#search'),tier=document.querySelector('#tier'),type=document.querySelector('#type'); [search,tier,type].forEach(x=>x.addEventListener('input',render)); render();
  function render(){const q=search.value.toLowerCase().trim();const rows=e.filter(x=>!tier.value||String(x.sourceTier)===tier.value).filter(x=>!type.value||x.recordType===type.value).filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).sort((a,b)=>(b.confidenceScore-a.confidenceScore)||(b.sourceTier-a.sourceTier));document.querySelector('#count').textContent='('+rows.length+')';document.querySelector('#evidence').innerHTML=rows.map(card).join('')||'<p>No matching evidence.</p>'}
  function card(x){const clues=(x.landClues||[]).map(v=>'<span class="pill">'+esc(v)+'</span>').join(' ');const warns=(x.contradictionFlags||[]).map(v=>'<div class="warn">⚠ '+esc(v)+'</div>').join('');return '<article class="card" data-tier="'+x.sourceTier+'"><h3>'+esc(x.title)+'</h3><div class="meta"><span class="pill">'+esc(x.targetName)+'</span><span class="pill">'+esc(x.recordType)+'</span><span class="pill">Tier '+x.sourceTier+'</span><span class="pill">'+x.confidenceScore+'/100</span><span class="pill">'+esc(x.verificationStatus)+'</span></div>'+(x.excerpt?'<p>'+esc(x.excerpt)+'</p>':'')+(clues?'<div class="land"><b>Land clues</b><div>'+clues+'</div></div>':'')+warns+'<p class="source"><a href="'+esc(x.sourceUrl)+'">'+esc(x.sourceUrl)+'</a></p></article>'}
  </script></body></html>`;
}

export function writeDashboard(html, outputFile = 'output/dashboard.html') {
  const file = path.resolve(process.cwd(), outputFile);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, html, 'utf8');
  return file;
}
